name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
        - name: ls
          run: |
            echo "Hello, world from github actions!" >> hola.txt
            cat hola.txt
